### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by Nekith**
Hello,

A proposal for the issue #45.

I've made these typings for a closed source project in TypeScript.

Just wanted to share them and work with you to integrate them upstream.

Cheers,

### CODE REVIEW

**Comment by kevinresol** [comment]
`getAll` should return `RNDefaultPreferenceKeys`

**Comment by Nekith** [comment]
Thank you for the quick answer.

It's done.
`getMultiple` should also, right?

**Comment by marcelkalveram** [comment]
Thanks @Nekith . I'll take a look at this today.

**Review by marcelkalveram — APPROVED** [review]
LGTM. Let's merge this.

**Pull request merged**
