### PR TITLE
Fallback from Cordova Native Storage Plugin

### PR DESCRIPTION
**Pull request by cristovao-trevisan**
I am upgrading my app from cordova to react-native, from each I was saving user data using cordova-plugin-native-storage, which uses SharedPreferences and UserDefaults, so I went into this module to do so.
The only thing not there already is the android preference name (different in that package), so I made a function to set it (and added instructions to the README)

### CODE REVIEW

**Comment by kevinresol** [comment]
Can you make the android function resolve a promise after the name is set?

**Comment by kevinresol** [comment]
And if you don't mind doing me a favor:

rename the function to be simply `setName`, then add `getName` as well

```java
@ReactMethod
public void setName(String preferencesName, Promise promise) {
  this.preferencesName = preferencesName;
  promise.resolve(null);
}

@ReactMethod
public void getName(Promise promise) {
  promise.resolve(preferencesName);
}
```

Extra: This would be super kind of you if you can also incorporate the ios implementation below

https://github.com/mswokk/react-native-default-preference/commit/089941f942b451ec12cc89fad60c5886b7252a00

(the major reason of needing a help is that I don't use this library actively now, so I don't have a setup to properly test it)

**Comment by cristovao-trevisan** [comment]
Did it for Android (and tested). I will do as asked for IOS tomorrow (it's now pretty late where I live), renaming `setDefaultSuite` to `setName` and adding an equivalent `getName` that returns the current value. Is that it?

I also feel like I am stealing that person's code, but for this repo usability I will do so mentioning here it is his/her work.

**Comment by kevinresol** [comment]
> Did it for Android (and tested). I will do as asked for IOS tomorrow (it's now pretty late where I live), renaming setDefaultSuite to setName and adding an equivalent getName that returns the current value. Is that it?

Yes, exactly

**Comment by cristovao-trevisan** [comment]
I did it. There were some problems with the newer version of react-native (resolver resulted in an extra parameter, needed to change it to resolve) but it's working now. Just to show my test, here is the code:

```javascript
DefaultPreference.clearAll().then(() => {
  DefaultPreference.get('key').then(value => {
    console.log(value)
    DefaultPreference.set('key', 'ok').then(() => {
      DefaultPreference.get('key').then(value => {
        console.log(value)
        DefaultPreference.setName('name').then(() => {
          DefaultPreference.getName().then(console.log)
          DefaultPreference.get('key').then(value => {
            console.log(value)
            DefaultPreference.set('key', 'ok').then(() => {
              DefaultPreference.get('key').then(console.log)
              DefaultPreference.clearAll()
              DefaultPreference.setName(null)
            })
          })
        })
      })
    })
  })
})

/* Expected Output:
 * - undefined
 * - ok
 * - name
 * - undefined
 * - ok
*/
```
And a snapshot proving it works:
screen shot 2017-10-10 at 3 37 35 pm

**Comment by kevinresol** [comment]
Thanks!

**Pull request merged**
