### PR TITLE
Create RNDefaultPreference.podspec

### PR DESCRIPTION
**Pull request by karanjthakkar**
Adds podspec to make it compatible with projects that use CocoaPods.

### CODE REVIEW

**Comment by kevinresol** [comment]
How is this used? (sorry I am not very familiar with cocoapod)

**Comment by karanjthakkar** [comment]
@kevinresol No problem. The usage for this would be like this: 

```
target 'myproject' do
  ....
  pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'
end
```

This would install `RNDefaultPreference` into a separate `Pods` project for iOS. Projects that use CocoaPods don't usually have a `Libraries` folder. 

I hope that makes sense. You can check out other react-native libraries that do this:
[react-native-safari-view](https://github.com/naoufal/react-native-safari-view/blob/master/react-native-safari-view.podspec)
[react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/RNI18n.podspec)
[react-native-device-info](https://github.com/rebeccahughes/react-native-device-info/blob/master/RNDeviceInfo.podspec)

**Comment by kevinresol** [comment]
Alright this looks great, let's have it :smile:

**Comment by karanjthakkar** [comment]
@kevinresol Thanks for the quick reply! Will you release a new version soon?

**Comment by kevinresol** [comment]
Sure, it is released as 1.1.0 now.

**Comment by karanjthakkar** [comment]
Awesome! Appreciate it 👍

**Pull request merged**
