### PR TITLE
add TypeScript index.d.ts file

### PR DESCRIPTION
**Pull request by AlanKeiss**
Just implemented https://github.com/kevinresol/react-native-default-preference/issues/45

### CODE REVIEW

**Comment by kevinresol** [comment]
I think `Object` should be something like `{ [key: string]: string; }`
But again I don't use TS so I am not exactly sure.

**Comment by marcelkalveram** [comment]
@AlanKeiss could you make the primitives lower-case? I'm getting this TS error in VS Code:

Screenshot 2019-10-28 09 39 48

**Comment by marcelkalveram** [comment]
@AlanKeiss thanks for the update.

I've justed tested the `setMultiple` and `getAll` method and realised they need to be typed with object instead of Maps:

```
static setMultiple(data: { [key:string] : string }): Promise<void>;
static getAll(): Promise<{ [key:string]:string }>;
```

**Comment by marcelkalveram** [comment]
@AlanKeiss opening this again, because it would be really good to have those typings. Did you close this on purpose, or did you just not want to implement the suggestion I added?

**Comment by marcelkalveram** [comment]
Has been resolved here: https://github.com/kevinresol/react-native-default-preference/pull/51

**Pull request closed without merging**
