### PR TITLE
add getObject, setObject, getArray, setArray

### PR DESCRIPTION
**Pull request by evanjmg**
Need to be able to fetch dictionaries

### CODE REVIEW

**Comment by kevinresol** [comment]
Please also implement for android and update the readme

**Comment by evanjmg** [comment]
Sorry will do ASAP

**Comment by evanjmg** [comment]
Hey @kevinresol, sorry it took so long for me to get to this. I tested this and it works on iphone SE and google pixel

**Comment by kevinresol** [comment]
I have decided that the scope of this library is to handle string values only. So closing this one.
Feel free to fork and create your own library.

**Pull request closed without merging**
