### PR TITLE
Added getObject to get dictionary values

### PR DESCRIPTION
**Pull request by anish531213**
I added a getObject export method that just get the dictionary for the key. I also tested it in my code and it work fine.

### CODE REVIEW

**Comment by kevinresol** [comment]
Thank you very much for the contribution, but I see a few problems here:

1. Missing android implementation
1. Most importantly: Doesn't fit in the API design (all data are string)

I suggest you take https://github.com/kevinresol/react-native-default-preference/pull/24/files and modify `arrayForKey` to `dataForKey`, so that you will get a Jsonified string for all the APIs (get, getMultiple, getAll)

**Comment by anish531213** [comment]
@kevinresol using dataForKey and converting the NSData to NSString, its giving me issues. Do you have any idea on that.

**Comment by anish531213** [comment]
@kevinresol  I have made changes to my implementation.

**Comment by kevinresol** [comment]
I still think that the solution by #24 is better: It tries to get string from the store first. If that fails, it will try to get object/dictionary/data from the store and then jsonify it. So that on js side we don't need a new API (getObject) but only `get/getMultiple/getAll`.

I am not sure if it is the best approach. Will anyone ever need to write object into the store?

**Comment by anish531213** [comment]
@kevinresol I couldn't use dataForKey and then convert that to string. That was the problem that led me to this solution. Yeah, #24 does try to solve that, but it is just working for string or array.

**Comment by kevinresol** [comment]
I have decided that the scope of this library is to handle string values only. So closing this one.
Feel free to fork and create your own library.

**Pull request closed without merging**
